// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyYorYRU0istmzJ_V3HRb4MycA6kuJurU',
    appId: '1:904946824619:web:044eae411e9f7b47850eee',
    messagingSenderId: '904946824619',
    projectId: 'capstone-89804',
    authDomain: 'capstone-89804.firebaseapp.com',
    storageBucket: 'capstone-89804.firebasestorage.app',
    measurementId: 'G-VZBENZKJL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAg5F0xRLCr3OFDQ67qGSDDqjx4zWN6ElA',
    appId: '1:1090862722356:android:e66b0e88c5be0daae90961',
    messagingSenderId: '1090862722356',
    projectId: 'flrm-9b3a0',
    storageBucket: 'flrm-9b3a0.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCyYorYRU0istmzJ_V3HRb4MycA6kuJurU',
    appId: '1:904946824619:web:f97d6bf3a3c369a9850eee',
    messagingSenderId: '904946824619',
    projectId: 'capstone-89804',
    authDomain: 'capstone-89804.firebaseapp.com',
    storageBucket: 'capstone-89804.firebasestorage.app',
    measurementId: 'G-13FGYH1KJY',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFHnd8qt3ZfX1cb-7ohat2LzOzqsDR50s',
    appId: '1:904946824619:ios:11562ba4d2fad56e850eee',
    messagingSenderId: '904946824619',
    projectId: 'capstone-89804',
    storageBucket: 'capstone-89804.firebasestorage.app',
    iosBundleId: 'com.example.app',
  );
}
